services:
  welephant:
    depends_on:
      db1:
        condition: service_healthy
      db2:
        condition: service_healthy
    build:
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: "./database_dumps"
        target: "/database_dumps"
    command:
      - "postgres://db1:db1@db1:5432/db1"
      - "postgres://db2:db2@db2:5432/db2"
      - "--dumps-directory=/database_dumps"

  db1:
    image: postgres
    environment:
      POSTGRES_USER: db1
      POSTGRES_PASSWORD: db2
    healthcheck: &postgres-healthcheck
      test:
        - "CMD-SHELL"
        - >-
          pg_isready
          --host=localhost
          --port=5432

  db2:
    image: postgres
    environment:
      POSTGRES_USER: db2
      POSTGRES_PASSWORD: db2
    healthcheck: *postgres-healthcheck
